config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'washers/show'
  root to: 'pages#index'

  get 'pages/index_washers'


  resources :prices
  resources :reconciliations
  resources :credit_notes
  resources :receipts
  resources :payments
  resources :vehicles
  resources :washes
  resources :vehicle_sizes
  resources :wash_types
  resources :places

  devise_for :users, controllers: {
          registrations: 'users/registrations'
        }

  devise_for :washers, controllers: {
          registrations: 'washers/registrations'
        }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :washers, only: [:index, :show]
  resources :users, only: [:index, :show]

end

app/controllers/wash_types_controller.rb
class WashTypesController < ApplicationController
  before_action :set_wash_type, only: [:show, :edit, :update, :destroy]

  # GET /wash_types
  # GET /wash_types.json
  def index
    @wash_types = WashType.all
  end

  # GET /wash_types/1
  # GET /wash_types/1.json
  def show
  end

  # GET /wash_types/new
  def new
    @wash_type = WashType.new
  end

  # GET /wash_types/1/edit
  def edit
  end

  # POST /wash_types
  # POST /wash_types.json
  def create
    @wash_type = WashType.new(wash_type_params)

    respond_to do |format|
      if @wash_type.save
        format.html { redirect_to @wash_type, notice: 'Wash type was successfully created.' }
        format.json { render :show, status: :created, location: @wash_type }
      else
        format.html { render :new }
        format.json { render json: @wash_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wash_types/1
  # PATCH/PUT /wash_types/1.json
  def update
    respond_to do |format|
      if @wash_type.update(wash_type_params)
        format.html { redirect_to @wash_type, notice: 'Wash type was successfully updated.' }
        format.json { render :show, status: :ok, location: @wash_type }
      else
        format.html { render :edit }
        format.json { render json: @wash_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wash_types/1
  # DELETE /wash_types/1.json
  def destroy
    @wash_type.destroy
    respond_to do |format|
      format.html { redirect_to wash_types_url, notice: 'Wash type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wash_type
      @wash_type = WashType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wash_type_params
      params.require(:wash_type).permit(:code, :name, :description)
    end
end

app/helpers/wash_types_helper.rb
module WashTypesHelper
end

app/views/wash_types/_form.html.erb
<%= form_with(model: wash_type, local: true) do |form| %>
  <% if wash_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wash_type.errors.count, "error") %> prohibited this wash_type from being saved:</h2>

      <ul>
      <% wash_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wash_types/edit.html.erb
<h1>Editing Wash Type</h1>

<%= render 'form', wash_type: @wash_type %>

<%= link_to 'Show', @wash_type %> |
<%= link_to 'Back', wash_types_path %>

app/views/wash_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wash Types</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wash_types.each do |wash_type| %>
      <tr>
        <td><%= wash_type.code %></td>
        <td><%= wash_type.name %></td>
        <td><%= wash_type.description %></td>
        <td><%= link_to 'Show', wash_type %></td>
        <td><%= link_to 'Edit', edit_wash_type_path(wash_type) %></td>
        <td><%= link_to 'Destroy', wash_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wash Type', new_wash_type_path %>

app/views/wash_types/new.html.erb
<h1>New Wash Type</h1>

<%= render 'form', wash_type: @wash_type %>

<%= link_to 'Back', wash_types_path %>

app/views/wash_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @wash_type.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @wash_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wash_type.description %>
</p>

<%= link_to 'Edit', edit_wash_type_path(@wash_type) %> |
<%= link_to 'Back', wash_types_path %>