config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'washers/show'
  root to: 'pages#index'

  get 'pages/index_washers'


  resources :prices
  resources :reconciliations
  resources :credit_notes
  resources :receipts
  resources :payments
  resources :vehicles
  resources :washes
  resources :vehicle_sizes
  resources :wash_types
  resources :places

  devise_for :users, controllers: {
          registrations: 'users/registrations'
        }

  devise_for :washers, controllers: {
          registrations: 'washers/registrations'
        }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :washers, only: [:index, :show]
  resources :users, only: [:index, :show]

end

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :reconciliations
  has_many :receipts, through: :reconciliations
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:bank, :statement_date, :document_number, :description, :received_amount, :commission, :comissioner, :user_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bank %>
    <%= form.text_field :bank %>
  </div>

  <div class="field">
    <%= form.label :statement_date %>
    <%= form.date_select :statement_date %>
  </div>

  <div class="field">
    <%= form.label :document_number %>
    <%= form.text_field :document_number %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :received_amount %>
    <%= form.number_field :received_amount %>
  </div>

  <div class="field">
    <%= form.label :commission %>
    <%= form.number_field :commission %>
  </div>

  <div class="field">
    <%= form.label :comissioner %>
    <%= form.text_field :comissioner %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Bank</th>
      <th>Statement date</th>
      <th>Document number</th>
      <th>Description</th>
      <th>Received amount</th>
      <th>Commission</th>
      <th>Comissioner</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.bank %></td>
        <td><%= payment.statement_date %></td>
        <td><%= payment.document_number %></td>
        <td><%= payment.description %></td>
        <td><%= payment.received_amount %></td>
        <td><%= payment.commission %></td>
        <td><%= payment.commissioner %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank:</strong>
  <%= @payment.bank %>
</p>

<p>
  <strong>Statement date:</strong>
  <%= @payment.statement_date %>
</p>

<p>
  <strong>Document number:</strong>
  <%= @payment.document_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payment.description %>
</p>

<p>
  <strong>Received amount:</strong>
  <%= @payment.received_amount %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @payment.commission %>
</p>

<p>
  <strong>Comissioner:</strong>
  <%= @payment.comissioner %>
</p>

<p>
  <strong>User:</strong>
  <%= @payment.user %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>