config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'washers/show'
  root to: 'pages#index'

  get 'pages/index_washers'


  resources :prices
  resources :reconciliations
  resources :credit_notes
  resources :receipts
  resources :payments
  resources :vehicles
  resources :washes
  resources :vehicle_sizes
  resources :wash_types
  resources :places

  devise_for :users, controllers: {
          registrations: 'users/registrations'
        }

  devise_for :washers, controllers: {
          registrations: 'washers/registrations'
        }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :washers, only: [:index, :show]
  resources :users, only: [:index, :show]

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle_size
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:patent, :type, :brand, :model, :color, :status, :user_id, :vehicle_size_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patent %>
    <%= form.text_field :patent %>
  </div>

  <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.text_field :vehicle_type %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :vehicle_size_id %>
    <%= form.text_field :vehicle_size_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Patent</th>
      <th>Type</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Color</th>
      <th>Status</th>
      <th>User</th>
      <th>Vehicle size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.patent %></td>
        <td><%= vehicle.vehicle_type %></td>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.status %></td>
        <td><%= vehicle.user %></td>
        <td><%= vehicle.vehicle_size %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patent:</strong>
  <%= @vehicle.patent %>
</p>

<p>
  <strong>Type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @vehicle.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<p>
  <strong>Status:</strong>
  <%= @vehicle.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @vehicle.user %>
</p>

<p>
  <strong>Vehicle size:</strong>
  <%= @vehicle.vehicle_size %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>