config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'washers/show'
  root to: 'pages#index'

  get 'pages/index_washers'


  resources :prices
  resources :reconciliations
  resources :credit_notes
  resources :receipts
  resources :payments
  resources :vehicles
  resources :washes
  resources :vehicle_sizes
  resources :wash_types
  resources :places

  devise_for :users, controllers: {
          registrations: 'users/registrations'
        }

  devise_for :washers, controllers: {
          registrations: 'washers/registrations'
        }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :washers, only: [:index, :show]
  resources :users, only: [:index, :show]

end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  has_many :reconciliations
  has_many :payments, through: :reconciliations
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:creation_date, :informed_gross_amount, :total_discount_amount, :sii_status, :user_id)
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_with(model: receipt, local: true) do |form| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :creation_date %>
    <%= form.date_select :creation_date %>
  </div>

  <div class="field">
    <%= form.label :informed_gross_amount %>
    <%= form.number_field :informed_gross_amount %>
  </div>

  <div class="field">
    <%= form.label :total_discount_amount %>
    <%= form.number_field :total_discount_amount %>
  </div>

  <div class="field">
    <%= form.label :sii_status %>
    <%= form.text_field :sii_status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Creation date</th>
      <th>Informed gross amount</th>
      <th>Total discount amount</th>
      <th>Sii status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.creation_date %></td>
        <td><%= receipt.informed_gross_amount %></td>
        <td><%= receipt.total_discount_amount %></td>
        <td><%= receipt.sii_status %></td>
        <td><%= receipt.user %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creation date:</strong>
  <%= @receipt.creation_date %>
</p>

<p>
  <strong>Informed gross amount:</strong>
  <%= @receipt.informed_gross_amount %>
</p>

<p>
  <strong>Total discount amount:</strong>
  <%= @receipt.total_discount_amount %>
</p>

<p>
  <strong>Sii status:</strong>
  <%= @receipt.sii_status %>
</p>

<p>
  <strong>User:</strong>
  <%= @receipt.user %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>